# Generated by Django 6.0.2 on 2026-03-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
    ]
